### ISSUE TITLE
No-MySQL-hostname-was-specified as MySQL Sock value?

### ISSUE THREAD

**Issue by meowsus** [goodguyry/dreambox#25]
I was curious about this line:
https://github.com/goodguyry/dreambox/blob/5fd3ed20ff9337a977e5833a677e03152c729fc3/src/php.sh#L99

I was just installing a platform via it's Installation Wizard and `/No-MySQL-hostname-was-specified` popped up as the value of my MySQL server socket field in the advanced settings.

This value seems like it was a relic from an automatic compilation, but I might be mistaken.

**Comment by goodguyry** [comment]
LOL nope, just a really bad copy-paste job :/ Thanks! 👍

**Comment by meowsus** [comment]
You know, it's funny. Ever since I opened this issue I've seen this No-MySQL-hostname-was-specified setting in so many other projects... never noticed it before!

Anyway, thanks. This is a great project.
