### ISSUE TITLE
getting started directions no longer lead to working system

### ISSUE THREAD

**Issue by acodispo** [goodguyry/dreambox#37]
I'm following [getting started](https://github.com/goodguyry/dreambox/wiki) but failing to end up with a usable system. Please advise what I'm doing wrong. I had previously been using dreambox 0.2.1 with no problems, but the new version doesn't seem to work.

This is an ubuntu box.

```shell
$ vagrant version
Installed Version: 1.9.7
Latest Version: 1.9.7
 
You're running an up-to-date version of Vagrant!
$ VBoxManage --version
5.1.26r117224
$ mkdir ~/dboxTest
$ cd ~/dboxTest
$ curl https://raw.githubusercontent.com/goodguyry/dreambox/master/Vagrantfile-example > Vagrantfile
$ mkdir web
$ vagrant up
[output, no errors displayed]
```

Browse to http://192.168.200.200/

All that is displayed is the Apache-default "It works!"

Adding `index.php` to the `web` subdirectory has no effect.

What am I missing?

Thanks!

**Comment by hawkeyeP** [comment]
I'm having the same problem.  It looks like SSL is automatically enabled regardless if you put true or false in the Vagrantfile.  If you got to https://yoursite.dev  it will load your index file.  I'm trying to figure out how to disable the SSL.  If you edit the httpd-vhosts it doesn't seem to do anything.

**Comment by goodguyry** [comment]
Shit. Sorry y'all. I've let this project slip. It was quiet for so long, I got a false sense of security...

**But** I think I know what's going on here.

https://github.com/goodguyry/dreambox/blob/master/files/user_setup#L219

That should be `[[ 'true' == $ENABLE_SSL ]]`, since it's converted to a string value when passed into Vagrant. I'll get this fixed tomorrow and send it up.

Thanks for reporting and sorry for the delay.

**Comment by acodispo** [comment]
@goodguyry Good to hear from you! No worries, I'll look forward to your update. :-)

**Comment by goodguyry** [comment]
Version 0.2.4 is up on Vagrant Cloud

https://app.vagrantup.com/goodguyry/boxes/dreambox/versions/0.2.4

`vagrant box update`

In my testing, the solution outlined in my previous comment fixes bug with SSL being perpetually enabled. Let me know if this clears up the issue on your end as well. Thanks!
