### ISSUE TITLE
Allow for multiple "domains" to be configured for the user.

### ISSUE THREAD

**Issue by NReilingh** [goodguyry/dreambox#5]
The way this box works right now, you can configure one user to be created, and one vhost to be created for the user. This maps well onto how most projects will exist on dreamhost in the wild, but some projects may span multiple domains. That is, a single site might use a few subdomains for different components, or someone could want to set up a development/staging/deployment environment with three different vhosts and DocumentRoots in the same user directory.

From a configuration standpoint, it would be great to see a way of defining a short list of vhosts for the user being provisioned, where each has a definable DocumentRoot, local project directory, and hostname.

(I would consider this to be a low-priority feature suggestion.)

**Comment by goodguyry** [comment]
This is fixed in v0.3.0
