### ISSUE TITLE
SSL no longer works (0.2.4; goodguyry/dreambox.box)

### ISSUE THREAD

**Issue by consumr** [goodguyry/dreambox#54]
Trying to use the 0.2.4 box (with the Vagrantfile-Example) and build were getting me a NET::ERR_CERT_COMMON_NAME_INVALID in Chrome 66, which I tracked down to actually be a subjectAltName issue.

From what I can tell, you've fixed this issue in 0.3.0, which I forked and managed to get running... for a little bit...

I'm writing this to you in hopes to encourage you to finish up the few things that are holding you back from releasing 0.3.0: I can't offer much, but could make a pull request to contribute the handful of things I found that help.

**Comment by goodguyry** [comment]
Thanks! Sorry for the late reply. I'll pick this back up soon and hopefully get 0.3.0 over the finish line.

**Comment by goodguyry** [comment]
Thinking more about this, I may just fix this in a patch if I can get it done quickly. If I recall correctly, it was a change in Chrome regarding what values they'll accept and where...

**Comment by goodguyry** [comment]
This is fixed in v0.3.0
