### ISSUE TITLE
Install and configure phpMyAdmin

### ISSUE THREAD

**Issue by NReilingh** [goodguyry/dreambox#6]
Another low priority enhancement suggestion:

Many people will be able to do what they need to do over the command line, but phpMyAdmin is part of the Dreamhost environment (4.6.0 is the current version).

Possibly related to #5, since the user would need to access the phpMyAdmin application, and doing this through a hostname (phpmyadmin.dreambox.dev?) would be a simple solution.

**Comment by goodguyry** [comment]
Relates to #38

**Comment by goodguyry** [comment]
This is fixed in v0.3.0
